Repository g59/nestjs-plugins, pull requests merged in 2020-03, with the labels that each got.

#15 chore: update usage
  README.md
  example/package.json
  package.json
  packages/nestjs-relay/README.md
  packages/nestjs-relay/package.json
  packages/variables/README.md
  packages/variables/package.json
  packages/variables/src/index.test.ts
  packages/variables/src/index.ts
  packages/variables/tsconfig.json
  yarn.lock
Labels: documentation

#16 fix: needs can-npm-publish
  example/package.json
  lerna.json
  package.json
  yarn.lock
Labels: bug

#17 fix: typo
  packages/nestjs-relay/package.json
Labels: bug

#18 chore: rename package
  README.md
  example/package.json
  example/src/recipes/dto/recipes.input.ts
  example/src/recipes/recipes.resolver.ts
  example/src/recipes/recipes.service.ts
  packages/nestjs-graphql-relay/README.md
  packages/nestjs-graphql-relay/__tests__/index.test.ts
  packages/nestjs-graphql-relay/package.json
  packages/nestjs-graphql-relay/src/aggregate.ts
  packages/nestjs-graphql-relay/src/connectionArgs.ts
  packages/nestjs-graphql-relay/src/index.ts
  packages/nestjs-graphql-relay/src/orderBy.input.ts
  packages/nestjs-graphql-relay/src/pageInfo.ts
  packages/nestjs-graphql-relay/tsconfig.json
Labels: enhancement

#19 chore: Added badge
  .gitignore
  README.md
  packages/nestjs-graphql-relay/README.md
Labels: documentation

#25 feat: nestjs-slack plugin
  .gitignore
  README.md
  example/package.json
  example/src/app.module.ts
  example/src/config/slack.ts
  example/src/notify/notify.controller.spec.ts
  example/src/notify/notify.controller.ts
  example/src/notify/notify.module.ts
  example/src/notify/notify.service.spec.ts
  example/src/notify/notify.service.ts
  example/src/testing/slack.ts
  packages/nestjs-slack/README.md
  packages/nestjs-slack/__tests__/getSlackClient.test.ts
  packages/nestjs-slack/__tests__/injectSlack.test.ts
  packages/nestjs-slack/__tests__/slackModule.test.ts
  packages/nestjs-slack/package.json
  packages/nestjs-slack/src/createSlackProvider.ts
  packages/nestjs-slack/src/getSlackClient.ts
  packages/nestjs-slack/src/index.ts
  packages/nestjs-slack/src/injectSlack.ts
  packages/nestjs-slack/src/slackConstants.ts
  packages/nestjs-slack/src/slackCoreModule.ts
  packages/nestjs-slack/src/slackModule.ts
  packages/nestjs-slack/src/slackOptions.ts
  packages/nestjs-slack/tsconfig.json
  yarn.lock
Labels: enhancement

#37 rename: package nestjs-slack-webhook
  README.md
  example/package.json
  example/src/app.module.ts
  example/src/notify/notify.service.ts
  example/src/testing/slack.ts
  packages/nestjs-slack-webhook/README.md
  packages/nestjs-slack-webhook/__tests__/getSlackClient.test.ts
  packages/nestjs-slack-webhook/__tests__/injectSlack.test.ts
  packages/nestjs-slack-webhook/__tests__/slackModule.test.ts
  packages/nestjs-slack-webhook/package.json
  packages/nestjs-slack-webhook/src/createSlackProvider.ts
  packages/nestjs-slack-webhook/src/getSlackClient.ts
  packages/nestjs-slack-webhook/src/index.ts
  packages/nestjs-slack-webhook/src/injectSlack.ts
  packages/nestjs-slack-webhook/src/slackConstants.ts
  packages/nestjs-slack-webhook/src/slackCoreModule.ts
  packages/nestjs-slack-webhook/src/slackModule.ts
  packages/nestjs-slack-webhook/src/slackOptions.ts
  packages/nestjs-slack-webhook/tsconfig.json
Labels: enhancement

#40 Bump v0.0.2
  .gitignore
  CHANGELOG.md
  example/package.json
  lerna.json
  package.json
  packages/nestjs-graphql-relay/package.json
  packages/nestjs-slack-webhook/package.json
Labels: documentation
